type Member {
  _id: ID!
  number: Int!
  fullName: String
  givenNames: String
  surname: String
  qualifications: [Qualification!]
  team: String
}

enum Qualification {
  CHAINSAW_CROSSCUT
  FLOOD_RESCUE_1
  FLOOD_RESCUE_2
  FLOOD_RESCUE_3
  LAND_SEARCH
  STORM_WATER_DAMAGE
  VERTICAL_RESCUE
}

type Team {
  name: String!
}

type Query {
  members: [Member!]!
  member(number: Int!): Member
}
